# Generated by Django 6.0.7 on 2026-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Untitled Job', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
