# Generated by Django 6.0.7 on 2026-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_company_alter_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
